void daughter_radial_distance_for_evt_with_at_least_one_prompt_np_by_signal_type()
{
//=========Macro generated from canvas: Canvas_1/Canvas_1
//=========  (Fri Aug  7 17:00:10 2020) by ROOT version 6.18/04
   TCanvas *Canvas_1 = new TCanvas("Canvas_1", "Canvas_1",662,115,1254,759);
   Canvas_1->Range(-125,-11.25,1125,101.25);
   Canvas_1->SetFillColor(0);
   Canvas_1->SetBorderMode(0);
   Canvas_1->SetBorderSize(2);
   Canvas_1->SetFrameBorderMode(0);
   Canvas_1->SetFrameBorderMode(0);
   
   TH1F *htemp__5 = new TH1F("htemp__5","daughter_radial_distance {num_Prompt_Pi2NP>0 && true_absSignal}",100,0,1000);
   htemp__5->SetBinContent(1,2);
   htemp__5->SetBinContent(2,7);
   htemp__5->SetBinContent(3,22);
   htemp__5->SetBinContent(4,71);
   htemp__5->SetBinContent(5,58);
   htemp__5->SetBinContent(6,60);
   htemp__5->SetBinContent(7,71);
   htemp__5->SetBinContent(8,54);
   htemp__5->SetBinContent(9,40);
   htemp__5->SetBinContent(10,34);
   htemp__5->SetBinContent(11,38);
   htemp__5->SetBinContent(12,46);
   htemp__5->SetBinContent(13,32);
   htemp__5->SetBinContent(14,31);
   htemp__5->SetBinContent(15,29);
   htemp__5->SetBinContent(16,18);
   htemp__5->SetBinContent(17,20);
   htemp__5->SetBinContent(18,10);
   htemp__5->SetBinContent(19,15);
   htemp__5->SetBinContent(20,20);
   htemp__5->SetBinContent(21,10);
   htemp__5->SetBinContent(22,5);
   htemp__5->SetBinContent(23,9);
   htemp__5->SetBinContent(24,12);
   htemp__5->SetBinContent(25,8);
   htemp__5->SetBinContent(26,6);
   htemp__5->SetBinContent(27,2);
   htemp__5->SetBinContent(28,7);
   htemp__5->SetBinContent(29,3);
   htemp__5->SetBinContent(30,3);
   htemp__5->SetBinContent(31,2);
   htemp__5->SetBinContent(32,1);
   htemp__5->SetBinContent(33,4);
   htemp__5->SetBinContent(34,13);
   htemp__5->SetBinContent(35,3);
   htemp__5->SetBinContent(36,5);
   htemp__5->SetBinContent(37,5);
   htemp__5->SetBinContent(38,11);
   htemp__5->SetBinContent(39,4);
   htemp__5->SetBinContent(40,1);
   htemp__5->SetBinContent(41,3);
   htemp__5->SetBinContent(42,1);
   htemp__5->SetBinContent(43,2);
   htemp__5->SetBinContent(44,2);
   htemp__5->SetBinContent(45,1);
   htemp__5->SetBinContent(46,2);
   htemp__5->SetBinContent(48,1);
   htemp__5->SetBinContent(65,1);
   htemp__5->SetBinContent(68,1);
   htemp__5->SetBinContent(93,1);
   htemp__5->SetMinimum(0);
   htemp__5->SetMaximum(90);
   htemp__5->SetEntries(807);
   htemp__5->SetDirectory(0);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *ptstats_LaTex = ptstats->AddText("htemp");
   ptstats_LaTex->SetTextSize(0.0368);
   ptstats_LaTex = ptstats->AddText("Entries = 807    ");
   ptstats_LaTex = ptstats->AddText("Mean  =  125.1");
   ptstats_LaTex = ptstats->AddText("Std Dev   =  100.6");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   htemp__5->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(htemp__5);
   htemp__5->SetLineColor(4);
   htemp__5->SetLineWidth(2);
   htemp__5->GetXaxis()->SetTitle("daughter_radial_distance");
   htemp__5->GetXaxis()->SetRange(1,100);
   htemp__5->GetXaxis()->SetLabelFont(42);
   htemp__5->GetXaxis()->SetLabelSize(0.035);
   htemp__5->GetXaxis()->SetTitleSize(0.035);
   htemp__5->GetXaxis()->SetTitleOffset(1);
   htemp__5->GetXaxis()->SetTitleFont(42);
   htemp__5->GetYaxis()->SetLabelFont(42);
   htemp__5->GetYaxis()->SetLabelSize(0.035);
   htemp__5->GetYaxis()->SetTitleSize(0.035);
   htemp__5->GetYaxis()->SetTitleFont(42);
   htemp__5->GetZaxis()->SetLabelFont(42);
   htemp__5->GetZaxis()->SetLabelSize(0.035);
   htemp__5->GetZaxis()->SetTitleSize(0.035);
   htemp__5->GetZaxis()->SetTitleOffset(1);
   htemp__5->GetZaxis()->SetTitleFont(42);
   htemp__5->Draw("");
   
   TPaveText *pt = new TPaveText(0.15,0.9347622,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("daughter_radial_distance {num_Prompt_Pi2NP>0 && true_absSignal}");
   pt->Draw();
   
   TH1F *htemp__6 = new TH1F("htemp__6","daughter_radial_distance {num_Prompt_Pi2NP>0 && true_chexSignal}",100,0,1000);
   htemp__6->SetBinContent(1,4);
   htemp__6->SetBinContent(2,7);
   htemp__6->SetBinContent(3,14);
   htemp__6->SetBinContent(4,20);
   htemp__6->SetBinContent(5,37);
   htemp__6->SetBinContent(6,39);
   htemp__6->SetBinContent(7,36);
   htemp__6->SetBinContent(8,36);
   htemp__6->SetBinContent(9,39);
   htemp__6->SetBinContent(10,29);
   htemp__6->SetBinContent(11,15);
   htemp__6->SetBinContent(12,19);
   htemp__6->SetBinContent(13,17);
   htemp__6->SetBinContent(14,12);
   htemp__6->SetBinContent(15,11);
   htemp__6->SetBinContent(16,16);
   htemp__6->SetBinContent(17,7);
   htemp__6->SetBinContent(18,1);
   htemp__6->SetBinContent(19,5);
   htemp__6->SetBinContent(20,3);
   htemp__6->SetBinContent(22,2);
   htemp__6->SetBinContent(26,1);
   htemp__6->SetBinContent(32,1);
   htemp__6->SetBinContent(33,1);
   htemp__6->SetBinContent(35,4);
   htemp__6->SetBinContent(36,4);
   htemp__6->SetBinContent(37,3);
   htemp__6->SetBinContent(38,3);
   htemp__6->SetBinContent(42,1);
   htemp__6->SetBinContent(43,1);
   htemp__6->SetBinContent(44,2);
   htemp__6->SetBinContent(45,1);
   htemp__6->SetBinContent(67,1);
   htemp__6->SetBinContent(78,1);
   htemp__6->SetBinContent(83,1);
   htemp__6->SetBinContent(85,1);
   htemp__6->SetBinContent(101,1);
   htemp__6->SetEntries(396);
   htemp__6->SetDirectory(0);
   htemp__6->SetLineColor(2);
   htemp__6->SetLineWidth(2);
   htemp__6->GetXaxis()->SetTitle("daughter_radial_distance");
   htemp__6->GetXaxis()->SetLabelFont(42);
   htemp__6->GetXaxis()->SetLabelSize(0.035);
   htemp__6->GetXaxis()->SetTitleSize(0.035);
   htemp__6->GetXaxis()->SetTitleOffset(1);
   htemp__6->GetXaxis()->SetTitleFont(42);
   htemp__6->GetYaxis()->SetLabelFont(42);
   htemp__6->GetYaxis()->SetLabelSize(0.035);
   htemp__6->GetYaxis()->SetTitleSize(0.035);
   htemp__6->GetYaxis()->SetTitleFont(42);
   htemp__6->GetZaxis()->SetLabelFont(42);
   htemp__6->GetZaxis()->SetLabelSize(0.035);
   htemp__6->GetZaxis()->SetTitleSize(0.035);
   htemp__6->GetZaxis()->SetTitleOffset(1);
   htemp__6->GetZaxis()->SetTitleFont(42);
   htemp__6->Draw("same");
   
   TH1F *htemp__7 = new TH1F("htemp__7","daughter_radial_distance {num_Prompt_Pi2NP>0 && true_nPi0Signal}",100,0,1000);
   htemp__7->SetBinContent(4,2);
   htemp__7->SetBinContent(5,3);
   htemp__7->SetBinContent(6,1);
   htemp__7->SetBinContent(7,1);
   htemp__7->SetBinContent(8,2);
   htemp__7->SetBinContent(9,2);
   htemp__7->SetBinContent(10,1);
   htemp__7->SetBinContent(14,1);
   htemp__7->SetBinContent(15,1);
   htemp__7->SetEntries(14);
   htemp__7->SetDirectory(0);
   htemp__7->SetLineColor(6);
   htemp__7->SetLineWidth(2);
   htemp__7->GetXaxis()->SetTitle("daughter_radial_distance");
   htemp__7->GetXaxis()->SetLabelFont(42);
   htemp__7->GetXaxis()->SetLabelSize(0.035);
   htemp__7->GetXaxis()->SetTitleSize(0.035);
   htemp__7->GetXaxis()->SetTitleOffset(1);
   htemp__7->GetXaxis()->SetTitleFont(42);
   htemp__7->GetYaxis()->SetLabelFont(42);
   htemp__7->GetYaxis()->SetLabelSize(0.035);
   htemp__7->GetYaxis()->SetTitleSize(0.035);
   htemp__7->GetYaxis()->SetTitleFont(42);
   htemp__7->GetZaxis()->SetLabelFont(42);
   htemp__7->GetZaxis()->SetLabelSize(0.035);
   htemp__7->GetZaxis()->SetTitleSize(0.035);
   htemp__7->GetZaxis()->SetTitleOffset(1);
   htemp__7->GetZaxis()->SetTitleFont(42);
   htemp__7->Draw("same");
   
   TH1F *htemp__8 = new TH1F("htemp__8","daughter_radial_distance {num_Prompt_Pi2NP>0 && true_backGround}",100,0,1000);
   htemp__8->SetBinContent(1,8);
   htemp__8->SetBinContent(2,26);
   htemp__8->SetBinContent(3,38);
   htemp__8->SetBinContent(4,82);
   htemp__8->SetBinContent(5,66);
   htemp__8->SetBinContent(6,76);
   htemp__8->SetBinContent(7,58);
   htemp__8->SetBinContent(8,72);
   htemp__8->SetBinContent(9,50);
   htemp__8->SetBinContent(10,33);
   htemp__8->SetBinContent(11,28);
   htemp__8->SetBinContent(12,27);
   htemp__8->SetBinContent(13,29);
   htemp__8->SetBinContent(14,22);
   htemp__8->SetBinContent(15,12);
   htemp__8->SetBinContent(16,10);
   htemp__8->SetBinContent(17,7);
   htemp__8->SetBinContent(18,9);
   htemp__8->SetBinContent(19,7);
   htemp__8->SetBinContent(20,8);
   htemp__8->SetBinContent(21,3);
   htemp__8->SetBinContent(22,9);
   htemp__8->SetBinContent(23,6);
   htemp__8->SetBinContent(24,3);
   htemp__8->SetBinContent(25,1);
   htemp__8->SetBinContent(26,2);
   htemp__8->SetBinContent(27,3);
   htemp__8->SetBinContent(28,4);
   htemp__8->SetBinContent(30,3);
   htemp__8->SetBinContent(31,4);
   htemp__8->SetBinContent(32,2);
   htemp__8->SetBinContent(33,2);
   htemp__8->SetBinContent(35,4);
   htemp__8->SetBinContent(36,5);
   htemp__8->SetBinContent(37,6);
   htemp__8->SetBinContent(38,1);
   htemp__8->SetBinContent(39,4);
   htemp__8->SetBinContent(40,1);
   htemp__8->SetBinContent(42,1);
   htemp__8->SetBinContent(44,1);
   htemp__8->SetBinContent(45,3);
   htemp__8->SetBinContent(51,1);
   htemp__8->SetBinContent(54,1);
   htemp__8->SetBinContent(64,1);
   htemp__8->SetBinContent(65,1);
   htemp__8->SetBinContent(69,1);
   htemp__8->SetBinContent(70,1);
   htemp__8->SetBinContent(75,1);
   htemp__8->SetBinContent(101,5);
   htemp__8->SetEntries(748);
   htemp__8->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#009900");
   htemp__8->SetLineColor(ci);
   htemp__8->SetLineWidth(2);
   htemp__8->GetXaxis()->SetTitle("daughter_radial_distance");
   htemp__8->GetXaxis()->SetLabelFont(42);
   htemp__8->GetXaxis()->SetLabelSize(0.035);
   htemp__8->GetXaxis()->SetTitleSize(0.035);
   htemp__8->GetXaxis()->SetTitleOffset(1);
   htemp__8->GetXaxis()->SetTitleFont(42);
   htemp__8->GetYaxis()->SetLabelFont(42);
   htemp__8->GetYaxis()->SetLabelSize(0.035);
   htemp__8->GetYaxis()->SetTitleSize(0.035);
   htemp__8->GetYaxis()->SetTitleFont(42);
   htemp__8->GetZaxis()->SetLabelFont(42);
   htemp__8->GetZaxis()->SetLabelSize(0.035);
   htemp__8->GetZaxis()->SetTitleSize(0.035);
   htemp__8->GetZaxis()->SetTitleOffset(1);
   htemp__8->GetZaxis()->SetTitleFont(42);
   htemp__8->Draw("same");
   
   TLegend *leg = new TLegend(0.2747604,0.5508587,0.5742812,0.7608983,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("htemp","daughter_radial_distance {num_Prompt_Pi2NP>0 && true_absSignal}","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("htemp","daughter_radial_distance {num_Prompt_Pi2NP>0 && true_chexSignal}","lpflpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("htemp","daughter_radial_distance {num_Prompt_Pi2NP>0 && true_nPi0Signal}","lpflpflpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("htemp","daughter_radial_distance {num_Prompt_Pi2NP>0 && true_backGround}","lpflpflpflpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#009900");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Canvas_1->Modified();
   Canvas_1->cd();
   Canvas_1->SetSelected(Canvas_1);
}
