void prompt_np_by_signal_type()
{
//=========Macro generated from canvas: Canvas_1/Canvas_1
//=========  (Fri Aug  7 16:53:15 2020) by ROOT version 6.18/04
   TCanvas *Canvas_1 = new TCanvas("Canvas_1", "Canvas_1",662,115,1254,759);
   Canvas_1->Range(-1,-175,9,1575);
   Canvas_1->SetFillColor(0);
   Canvas_1->SetBorderMode(0);
   Canvas_1->SetBorderSize(2);
   Canvas_1->SetFrameBorderMode(0);
   Canvas_1->SetFrameBorderMode(0);
   
   TH1F *htemp = new TH1F("htemp","num_Prompt_Pi2NP {true_beam_PDG==211 && true_absSignal}",8,0,8);
   htemp->SetBinContent(1,318);
   htemp->SetBinContent(2,241);
   htemp->SetBinContent(3,194);
   htemp->SetBinContent(4,130);
   htemp->SetBinContent(5,61);
   htemp->SetBinContent(6,25);
   htemp->SetBinContent(7,10);
   htemp->SetBinContent(8,3);
   htemp->SetMinimum(0);
   htemp->SetMaximum(1400);
   htemp->SetEntries(982);
   htemp->SetDirectory(0);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *ptstats_LaTex = ptstats->AddText("htemp");
   ptstats_LaTex->SetTextSize(0.0368);
   ptstats_LaTex = ptstats->AddText("Entries = 982    ");
   ptstats_LaTex = ptstats->AddText("Mean  =  1.496");
   ptstats_LaTex = ptstats->AddText("Std Dev   =  1.461");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   htemp->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(htemp);
   htemp->SetLineColor(4);
   htemp->SetLineWidth(2);
   htemp->GetXaxis()->SetTitle("num_Prompt_Pi2NP");
   htemp->GetXaxis()->SetRange(1,100);
   htemp->GetXaxis()->SetLabelFont(42);
   htemp->GetXaxis()->SetLabelSize(0.035);
   htemp->GetXaxis()->SetTitleSize(0.035);
   htemp->GetXaxis()->SetTitleOffset(1);
   htemp->GetXaxis()->SetTitleFont(42);
   htemp->GetYaxis()->SetLabelFont(42);
   htemp->GetYaxis()->SetLabelSize(0.035);
   htemp->GetYaxis()->SetTitleSize(0.035);
   htemp->GetYaxis()->SetTitleFont(42);
   htemp->GetZaxis()->SetLabelFont(42);
   htemp->GetZaxis()->SetLabelSize(0.035);
   htemp->GetZaxis()->SetTitleSize(0.035);
   htemp->GetZaxis()->SetTitleOffset(1);
   htemp->GetZaxis()->SetTitleFont(42);
   htemp->Draw("colz");
   
   TPaveText *pt = new TPaveText(0.15,0.9347622,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("num_Prompt_Pi2NP {true_beam_PDG==211 && true_absSignal}");
   pt->Draw();
   
   TH1F *htemp__2 = new TH1F("htemp__2","num_Prompt_Pi2NP {true_beam_PDG==211 && true_chexSignal}",8,0,8);
   htemp__2->SetBinContent(1,379);
   htemp__2->SetBinContent(2,111);
   htemp__2->SetBinContent(3,49);
   htemp__2->SetBinContent(4,23);
   htemp__2->SetBinContent(5,8);
   htemp__2->SetBinContent(6,2);
   htemp__2->SetEntries(572);
   htemp__2->SetDirectory(0);
   htemp__2->SetLineColor(2);
   htemp__2->SetLineWidth(2);
   htemp__2->GetXaxis()->SetTitle("num_Prompt_Pi2NP");
   htemp__2->GetXaxis()->SetLabelFont(42);
   htemp__2->GetXaxis()->SetLabelSize(0.035);
   htemp__2->GetXaxis()->SetTitleSize(0.035);
   htemp__2->GetXaxis()->SetTitleOffset(1);
   htemp__2->GetXaxis()->SetTitleFont(42);
   htemp__2->GetYaxis()->SetLabelFont(42);
   htemp__2->GetYaxis()->SetLabelSize(0.035);
   htemp__2->GetYaxis()->SetTitleSize(0.035);
   htemp__2->GetYaxis()->SetTitleFont(42);
   htemp__2->GetZaxis()->SetLabelFont(42);
   htemp__2->GetZaxis()->SetLabelSize(0.035);
   htemp__2->GetZaxis()->SetTitleSize(0.035);
   htemp__2->GetZaxis()->SetTitleOffset(1);
   htemp__2->GetZaxis()->SetTitleFont(42);
   htemp__2->Draw("same");
   
   TH1F *htemp__3 = new TH1F("htemp__3","num_Prompt_Pi2NP {true_beam_PDG==211 && true_nPi0Signal}",8,0,8);
   htemp__3->SetBinContent(1,72);
   htemp__3->SetBinContent(2,6);
   htemp__3->SetBinContent(3,5);
   htemp__3->SetEntries(83);
   htemp__3->SetDirectory(0);
   htemp__3->SetLineColor(7);
   htemp__3->SetLineWidth(2);
   htemp__3->GetXaxis()->SetTitle("num_Prompt_Pi2NP");
   htemp__3->GetXaxis()->SetLabelFont(42);
   htemp__3->GetXaxis()->SetLabelSize(0.035);
   htemp__3->GetXaxis()->SetTitleSize(0.035);
   htemp__3->GetXaxis()->SetTitleOffset(1);
   htemp__3->GetXaxis()->SetTitleFont(42);
   htemp__3->GetYaxis()->SetLabelFont(42);
   htemp__3->GetYaxis()->SetLabelSize(0.035);
   htemp__3->GetYaxis()->SetTitleSize(0.035);
   htemp__3->GetYaxis()->SetTitleFont(42);
   htemp__3->GetZaxis()->SetLabelFont(42);
   htemp__3->GetZaxis()->SetLabelSize(0.035);
   htemp__3->GetZaxis()->SetTitleSize(0.035);
   htemp__3->GetZaxis()->SetTitleOffset(1);
   htemp__3->GetZaxis()->SetTitleFont(42);
   htemp__3->Draw("same");
   
   TH1F *htemp__4 = new TH1F("htemp__4","num_Prompt_Pi2NP {true_beam_PDG==211 && true_backGround}",8,0,8);
   htemp__4->SetBinContent(1,1312);
   htemp__4->SetBinContent(2,238);
   htemp__4->SetBinContent(3,129);
   htemp__4->SetBinContent(4,31);
   htemp__4->SetBinContent(5,17);
   htemp__4->SetBinContent(6,2);
   htemp__4->SetEntries(1729);
   htemp__4->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#009900");
   htemp__4->SetLineColor(ci);
   htemp__4->SetLineWidth(2);
   htemp__4->GetXaxis()->SetTitle("num_Prompt_Pi2NP");
   htemp__4->GetXaxis()->SetLabelFont(42);
   htemp__4->GetXaxis()->SetLabelSize(0.035);
   htemp__4->GetXaxis()->SetTitleSize(0.035);
   htemp__4->GetXaxis()->SetTitleOffset(1);
   htemp__4->GetXaxis()->SetTitleFont(42);
   htemp__4->GetYaxis()->SetLabelFont(42);
   htemp__4->GetYaxis()->SetLabelSize(0.035);
   htemp__4->GetYaxis()->SetTitleSize(0.035);
   htemp__4->GetYaxis()->SetTitleFont(42);
   htemp__4->GetZaxis()->SetLabelFont(42);
   htemp__4->GetZaxis()->SetLabelSize(0.035);
   htemp__4->GetZaxis()->SetTitleSize(0.035);
   htemp__4->GetZaxis()->SetTitleOffset(1);
   htemp__4->GetZaxis()->SetTitleFont(42);
   htemp__4->Draw("same");
   
   TLegend *leg = new TLegend(0.4504792,0.3956407,0.75,0.6056803,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("htemp","num_Prompt_Pi2NP {true_beam_PDG==211 && true_absSignal}","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("htemp","num_Prompt_Pi2NP {true_beam_PDG==211 && true_chexSignal}","lpflpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("htemp","num_Prompt_Pi2NP {true_beam_PDG==211 && true_nPi0Signal}","lpflpflpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(7);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("htemp","num_Prompt_Pi2NP {true_beam_PDG==211 && true_backGround}","lpflpflpflpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#009900");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Canvas_1->Modified();
   Canvas_1->cd();
   Canvas_1->SetSelected(Canvas_1);
}
